import React from 'react';
import Heading from '../UI/GoPayraHeading';

const PrivacyPolicy = () => {
  return (
    <div className='mt-40 text-black px-8'>
      <div className='text-center my-8'>
        <Heading
          heading="PRIVACY POLICY"
        />
      </div>
      {/* condition 1 */}
      <div className="conditions policy">
        <h1>1. Introduction</h1>
        <h2>Welcome to GoPayra</h2>
        <p>GoPayra (“us”, “we”, or “our”) operates <a href="https://gopayra.com/">gopayra.com</a> (hereinafter referred to as “Service”).</p>
        <p>Our Privacy Policy governs your visit to <a href="https://gopayra.com/">gopayra.com</a>, and explains how we collect, safeguard and disclose information that results from your use of our Service.</p>
        <p>We use your data to provide and improve Service. By using Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions.</p>
        <p>Our Terms and Conditions (“Terms”) govern all use of our Service and together with the Privacy Policy constitutes your agreement with us (“agreement”).</p>

        <h1>2. Definitions</h1>
        <h5>SERVICE means the <a href="https://gopayra.com/">gopayra.com</a> website operated by GoPayra</h5>
        <p>PERSONAL DATA means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).</p>
        <p>USAGE DATA is data collected automatically either generated by the use of Service or from Service infrastructure itself (for example, the duration of a page visit).</p>
        <p>COOKIES are small files stored on your device (computer or mobile device).</p>
        <p>DATA CONTROLLER means a natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal data are, or are to be, processed. For the purpose of this Privacy Policy, we are a Data Controller of your data.</p>
        <p>DATA PROCESSORS (OR SERVICE PROVIDERS) means any natural or legal person who processes the data on behalf of the Data Controller. We may use the services of various Service Providers in order to process your data more effectively.</p>
        <p>DATA SUBJECT is any living individual who is the subject of Personal Data.</p>
        <p>THE USER is the individual using our Service. The User corresponds to the Data Subject, who is the subject of Personal Data.</p>

        <h1>3. Information Collection and Use</h1>
        <p>We collect several different types of information for various purposes to provide and improve our Service to you.</p>

        <h1>4. Types of Data Collected</h1>
        <h5>Personal Data</h5>
        <p>While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you (“Personal Data”).</p>
        <ol>Personally identifiable information may include, but is not limited to:
          <li>0.1. Email address</li>
          <li>0.2. First name and last name</li>
          <li>0.3. Phone number</li>
          <li>0.4. Address, State, Province, ZIP/Postal code, City</li>
          <li>0.5. Cookies and Usage Data</li>
        </ol>
        <p>We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us by following the unsubscribe link.</p>

        <h5>Usage Data</h5>
        <p>We may also collect information that your browser sends whenever you visit our Service or when you access Service by or through a mobile device (“Usage Data”).</p>
        <p>This Usage Data may include information such as your computer&apos;s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
        <p>When you access Service with a mobile device, this Usage Data may include information such as the type of mobile device you use, your mobile device unique ID, the IP address of your mobile device, your mobile operating system, the type of mobile Internet browser you use, unique device identifiers and other diagnostic data.</p>

        <h5>Location Data</h5>
        <p>We may use and store information about your location if you give us permission to do so (“Location Data”). We use this data to provide features of our Service, to improve and customize our Service.</p>
        <p>You can enable or disable location services when you use our Service at any time by way of your device settings.</p>

        <h5>Location Data - GoPayra AGENT App</h5>
        <p>To participate as a GoPayra driver, you must permit the GoPayra Services to access location services through the permission system used by your mobile operating system (“Platform”) or browser. We may collect the precise location of your device when the GoPayra app is running in the foreground or background of your device. We may also derive your approximate location from your IP address. We use your location information to verify that you are present in your preferred region or city when you begin or engage in a delivery through the GoPayra (a “Delivery”), connect you with delivery opportunities in your zone, and track the progress and completion of your Deliveries. You can enable the location tracking feature through the settings on your device or Platform or when prompted by the GoPayra mobile app. If you choose to disable the location feature through the settings on your device or Platform, GoPayra will not receive precise location information from your device, which will prevent you from being able to Trip and receiving delivery opportunities in your area.</p>

        <h5>Tracking Cookies Data</h5>
        <p>We use cookies and similar tracking technologies to track the activity on our Service and we hold certain information.</p>
        <p>Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Other tracking technologies are also used such as beacons, tags and scripts to collect and track information and to improve and analyze our Service.</p>
        <p>You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.</p>

        <ul>Examples of Cookies we use:
          <li>4.1. Session Cookies: We use Session Cookies to operate our Service.</li>
          <li>4.2. Preference Cookies: We use Preference Cookies to remember your preferences and various settings.</li>
          <li>4.3. Security Cookies: We use Security Cookies for security purposes.</li>
          <li>4.4. Advertising Cookies: Advertising Cookies are used to serve you with advertisements that may be relevant to you and your interests.</li>
        </ul>

        <h5>Other Data</h5>
        <p>While using our Service, we may also collect the following information: sex, age, date of birth, place of birth, passport details, citizenship, registration at place of residence and actual address, telephone number (work, mobile), details of documents on education, qualification, professional training, employment agreements, non-disclosure agreements, information on bonuses and compensation, information on marital status, family members, social security (or other taxpayer identification) number, office location and other data.</p>

        <h1>5. Use of Data</h1>
        <h5>GoPayra uses the collected data for various purposes:</h5>
        <ol>
          <li>0.1. to provide and maintain our Service;</li>
          <li>0.2. to notify you about changes to our Service;</li>
          <li>0.3. to allow you to participate in interactive features of our Service when you choose to do so;</li>
          <li>0.4. to provide customer support;</li>
          <li>0.5. to gather analysis or valuable information so that we can improve our Service;</li>
          <li>0.6. to monitor the usage of our Service;</li>
          <li>0.7. to detect, prevent and address technical issues;</li>
          <li>0.8. to fulfill any other purpose for which you provide it;</li>
          <li>0.9. to carry out our obligations and enforce our rights arising from any contracts entered into between you and us, including for billing and collection;</li>
          <li>0.10. to provide you with notices about your account and/or subscription, including expiration and renewal notices, email-instructions, etc.;</li>
          <li>0.11. to provide you with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information;</li>
          <li>0.12. in any other way we may describe when you provide the information;</li>
          <li>0.13. for any other purpose with your consent.</li>
        </ol>

        <h1>6. Retention of Data</h1>
        <p>We will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</p>
        <p>We will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer time periods.</p>

        <h1>7. Transfer of Data</h1>
        <p>Your information, including Personal Data, may be transferred to - and maintained on - computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction.</p>
        <p>If you are located outside United States, Puerto Rico and choose to provide information to us, please note that we transfer the data, including Personal Data, to United States, Puerto Rico and process it there.</p>
        <p>Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.</p>
        <p>GoPayra will take all the steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organisation or a country unless there are adequate controls in place including the security of your data and other personal information.</p>

        <h1>8. Disclosure of Data</h1>
        <h2>We may disclose personal information that we collect, or you provide:</h2>
        <h5>0.1. Disclosure for Law Enforcement.</h5>
        <p>Under certain circumstances, we may be required to disclose your Personal Data if required to do so by law or in response to valid requests by public authorities.</p>

        <h5>0.2. Business Transaction.</h5>
        <p>If we or our subsidiaries are involved in a merger, acquisition or asset sale, your Personal Data may be transferred.</p>

        <h5>0.3. Other cases. We may disclose your information also:</h5>
        <ol>
          <li>0.3.1. to our subsidiaries and affiliates;</li>
          <li>0.3.2. to contractors, service providers, and other third parties we use to support our business;</li>
          <li>0.3.3. to fulfill the purpose for which you provide it;</li>
          <li>0.3.4. for the purpose of including your company&apos;s logo on our website;</li>
          <li>0.3.5. for any other purpose disclosed by us when you provide the information;</li>
          <li>0.3.6. with your consent in any other cases;</li>
          <li>0.3.7. if we believe disclosure is necessary or appropriate to protect the rights, property, or safety of the Company, our customers, or others.</li>
        </ol>

        <h1>9. Security of Data</h1>
        <p>The security of your data is important to us but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.</p>

        <h1>10. Service Providers</h1>
        <p>We may employ third-party companies and individuals to facilitate our Service (“Service Providers”), provide Service on our behalf, perform Service-related services or assist us in analyzing how our Service is used.</p>
        <p>These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.</p>

        <h1>11. Analytics</h1>
        <p>We may use third-party Service Providers to monitor and analyze the use of our Service.</p>

        <h1>12. CI/CD tools</h1>
        <p>We may use third-party Service Providers to automate the development process of our Service.</p>

        <h1>13. Advertising</h1>
        <p>We may use third-party Service Providers to show advertisements to you to help support and maintain our Service.</p>

        <h1>14. Behavioral Remarketing</h1>
        <p>We may use remarketing services to advertise on third party websites to you after you visited our Service. We and our third-party vendors use cookies to inform, optimise and serve ads based on your past visits to our Service.</p>

        <h1>15. Payments</h1>
        <p>We may provide paid products and/or services within Service. In that case, we use third-party services for payment processing (e.g. payment processors).</p>
        <p>We will not store or collect your payment card details. That information is provided directly to our third-party payment processors whose use of your personal information is governed by their Privacy Policy. These payment processors adhere to the standards set by PCI-DSS as managed by the PCI Security Standards Council, which is a joint effort of brands like Visa, Mastercard, American Express and Discover. PCI-DSS requirements help ensure the secure handling of payment information.</p>

        <h1>16. Links to Other Sites</h1>
        <p>Our Service may contain links to other sites that are not operated by us. If you click a third party link, you will be directed to that third party&apos;s site. We strongly advise you to review the Privacy Policy of every site you visit.</p>
        <p>We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>
        <p>For example, the outlined Privacy Policy has been created using PolicyMaker.io, a free web application for generating high-quality legal documents.</p>
        <p>PolicyMaker&apos;s online privacy policy generator is an easy-to-use free tool for creating an excellent privacy policy template for a website, blog, online store or app.</p>

        <h1>17. Children&apos;s Privacy</h1>
        <p>Our Services are not intended for use by children under the age of 18 (“Child” or “Children”).</p>
        <p>We do not knowingly collect personally identifiable information from Children under 18. If you become aware that a Child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from Children without verification of parental consent, we take steps to remove that information from our servers.</p>

        <h1>18. Changes to This Privacy Policy</h1>
        <p>We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.</p>
        <p>We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective and update “effective date” at the top of this Privacy Policy.</p>
        <p>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>

        <h1>19. Contact Us</h1>
        <p>If you have any questions about this Privacy Policy, please contact us by email: support@gopayra.com</p>
      </div>
    </div>
  );
};

export default PrivacyPolicy;